name: CI
on:
  #push:
    #branches: [ main ]
  #pull_request:
    #branches: [ main ]
  workflow_dispatch:

jobs:
  test-job:
    runs-on: ubuntu-latest
    name: docker action
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Docker
        uses: ./local_action
