name: CI
on:
  #push:
    #branches: [ main ]
  #pull_request:
    #branches: [ main ]
  workflow_dispatch:

jobs:
  test-job:
    name: Use double quotes
    if: github.event_name != "workflow_dispatch"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
  build:
    runs-on: [ macos-latest ]
    steps:
    - name: test
      run: |
        echo '${{ inputs.github_context }}'

