name: Issue 1445

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set env to prod
        run: |
          pwd
          echo $GITHUB_ENV
          echo "ENV_NAME=prod" >> $GITHUB_ENV
      - name: Echo ENV_NAME
        run: echo $ENV_NAME
