name: Issue1416
on:
  #push:
    #branches: [ main ]
  #pull_request:
    #branches: [ main ]
  workflow_dispatch:

jobs:
  test-job:
    runs-on: self-hosted
    name: docker action
    steps:
      - name: checkout
        using: actions/checkout@v2
      - name: Action a
        uisng: ./.github/action-a
      - name: Root action
        using: ./
