name: Issue1416
on:
  #push:
    #branches: [ main ]
  #pull_request:
    #branches: [ main ]
  workflow_dispatch:

jobs:
  test-job:
    runs-on: self-hosted
    name: docker action
    steps:
      - name: Action a
        uses: ./action-a
