name: Testspace
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Job name'
        required: true
jobs:
  test:
    if: ${{'test' == github.event.inputs.name}}
    runs-on: ubuntu-latest
    steps:
      - run: echo example ${{ github.job }} job run
